---
title: "LTCOPDsex"
author: "dmorgan"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
library(knitr,HumanHT12v4.0Manifest)
knitr::opts_chunk$set(echo = TRUE)
(s = system.file("examples", "knitr-spin.R", package = "knitr"))
o = spin(s, knit = FALSE, format = "Rhtml")  # convert to Rmd only
knit2html(o)  # compile to HTML

```

## Load RAW LTCOPD expression data

```{r,echo=False}
################################################################
#   Boxplot for selected GEO samples
library(Biobase)
library(GEOquery)

# load series and platform data from GEO

gset <- getGEO("GSE76925", GSEMatrix =TRUE, getGPL=FALSE)
if (length(gset) > 1) idx <- grep("GPL10558", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

```

## Including Plots

Boxplot of exp distr:

```{r}
# set parameters and draw the plot
dev.new(width=4+dim(gset)[[2]]/5, height=6)
par(mar=c(2+round(max(nchar(sampleNames(gset)))/2),4,2,1))
title <- paste ("GSE76925", '/', annotation(gset), " selected samples", sep ='')
boxplot(exprs(gset), boxwex=0.7, notch=T, main=title, outline=FALSE, las=2)

```
```{r}
data<-exprs(gset)
library(readr,illuminaio)
HumanHT_12_V4_0_R2_15002873_B <- read_delim("~/data/GSE76925_RAW/HumanHT-12_V4_0_R2_15002873_B.txt", "\t", escape_double = FALSE, trim_ws = TRUE, skip = 8)
jj<-data.frame(bgx$Probe_Id)
jj$gene<-bgx$ILMN_Gene

bgx<-readBGX("~/data/GSE76925_RAW/HumanHT-12_V4_0_R2_15002873_B")
data2 <- read_delim("~/data/GSE76925_RAW/GSE76925_non-normalized.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
data3<-merge(data2,jj,by.x='X1',by.y='HumanHT_12_V4_0_R2_15002873_B.Probe_Id')

```



